slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/AC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_AC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/BC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_BC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/Cone.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_Cone/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/HC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_HC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/RGC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_RGC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/Rod.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_Rod/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/NRPC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_NRPC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/PRPC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_PRPC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/RPC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_RPC/adata_umap.h5ad
slurmtaco.sh -p gpu -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/MG.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_MG/adata_umap.h5ad

export CUDA_VISIBLE_DEVICES=0
slurmtaco.sh --g01 -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/BC_Rod_Cone.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_BC_Rod_Cone/adata_umap.h5ad
export CUDA_VISIBLE_DEVICES=1
slurmtaco.sh --g01 -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/AC_HC_RGC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_AC_HC_RGC/adata_umap.h5ad
export CUDA_VISIBLE_DEVICES=2
slurmtaco.sh --g01 -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/PRPC_MG.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_PRPC_MG/adata_umap.h5ad

slurmtaco.sh --g01 -m 50G -t 1 --30day -- python3 multivelo_recover_dynamics_run_umap.py /storage/singlecell/zz4/fetal_bash/results/MultiVelo_filtered_cells/adata_rna.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_knn_smooth_chrom/NRPC.h5ad /storage/singlecell/zz4/fetal_bash/results/multivelo_recover_dynamics_run_umap_NRPC/adata_umap.h5ad