groups = [
    "AC",
    "HC",
    "RGC",
    "BC",
    "Cone",
    "Rod",
    "AC_HC_RGC",
    "BC_Rod_Cone",
    "Annotated_NRPC",
]
meta_list = [
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/AC.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/HC.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/RGC.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/BC.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/Cone.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/Rod.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/AC_HC_RGC.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/BC_Rod_Cone.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/Annotated_NRPC.csv",
]

sample2meta = dict(zip(groups, meta_list))


def get_meta(wildcards):
    return sample2meta[wildcards.sam]


rule all:
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/Annotated_NRPC.csv",
        expand(
            [
                "/storage/singlecell/zz4/fetal_snakemake/results/pando_results/{sam}_seurat_object.rds",
            ],
            sam=groups,
        ),


rule NRPC_meta:
    ## Split NRPC files to generate meta
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC_fate.csv",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/NRPC_fate/NRPC/Annotated_NRPC.csv",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/pando/NRPC_meta/NRPC_meta.R'
        """

rule run_pando:
    ## Run pando
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/merged_rna/merged_rna.rds",
        meta=get_meta,
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/pando_results/{sam}_seurat_object.rds",
        "/storage/singlecell/zz4/fetal_snakemake/results/pando_results/{sam}_modules_meta.csv",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/pando/run_pando/run_pando.R {wildcards.sam} {input.meta}'
        """
