import pandas as pd
celltypes = ["RGC", "HC", "NRPC", "PRPC", "Cone", "MG", "AC", "BC", "Rod"]

rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_rna/merged_rna.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/pando_merged_seurat_object/pando_merged_seurat_object.rds",
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/pando_merged_seurat_object/pando_merged_seurat_object_{celltype}.rds",
            ],
            celltype=celltypes,
        ),
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/pando_results/pando_{celltype}.rds"
            ],
            celltype=celltypes,
        )

rule merge_ATAC:
    ## Create ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/Multi_Fetal_23w1d_NR/outs/atac_fragments.tsv.gz",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_atac/atac.rds"
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Pando/merge_ATAC/merge_ATAC.R'
        """

rule merge_RNA:
    ## Create ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/Multi_Fetal_23w1d_NR/outs/atac_fragments.tsv.gz",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_rna/merged_rna.rds"
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Pando/merge_RNA/merge_RNA.R'
        """

rule create_seurat_object:
    ## Create ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_rna/merged_rna.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_atac/atac.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/ALL.csv"
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/pando_merged_seurat_object/pando_merged_seurat_object.rds"
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Pando/create_seurat_object/create_seurat_object.R'
        """

rule split_by_class:
    ## Create ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_rna/merged_rna.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_atac/atac.rds",
        "/storage/chentemp/zz4/adult_dev_compare/scripts/Pando/split_by_class/split_by_class.R"
    output:
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/pando_merged_seurat_object/pando_merged_seurat_object_{celltype}.rds",
            ],
            celltype=celltypes,
        )
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Pando/split_by_class/split_by_class.R'
        """

rule run_pando_majorclass:
    ## Create ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/pando_merged_seurat_object/pando_merged_seurat_object_{celltype}.rds"
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/pando_results/pando_{celltype}.rds"
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate newR
        /storage/chen/home/zz4/miniforge-pypy3/envs/newR/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Pando/run_pando_majorclass/run_pando_majorclass.R /storage/chentemp/zz4/adult_dev_compare/results/pando_merged_seurat_object/pando_merged_seurat_object_{wildcards.celltype}.rds {wildcards.celltype}'
        """