import pandas as pd

meta = pd.read_csv(
    "/storage/singlecell/zz4/fetal_snakemake/scripts/Volocity/velocyto/meta.csv"
)
samples = meta["samples"].tolist()
sample2barcodes = dict(zip(meta["samples"].tolist(), meta["barcodes"].tolist()))
sample2bams = dict(zip(meta["samples"].tolist(), meta["bams"].tolist()))
genome = "/storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf"


def get_barcodes(wildcards):
    return sample2barcodes[wildcards.sample]


def get_bam(wildcards):
    return sample2bams[wildcards.sample]


rule all:
    input:
        expand(
            [
                "/storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/{sample}.loom",
            ],
            sample=samples,
        ),
        "/storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/10x3_Lobe_19_D019_NeuN-v7.loom"


rule velocyto:
    ## Run velocyto
    input:
        get_barcodes,
        get_bam,
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/{sample}.loom",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate velocyto
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        mkdir /storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/
        velocyto run -o /storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/ -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_snakemake/data/Retina_fetal/{wildcards.sample}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e {wildcards.sample} /storage/singlecell/zz4/fetal_snakemake/data/Retina_fetal/{wildcards.sample}/outs/gex_possorted_bam.bam {genome}'
        """

rule velocyto_adult:
    ## Run velocyto
    input:
        "/storage/singlecell/zz4/fetal_snakemake/data/adult_data/10x3_Lobe_19_D019_NeuN-v7/filtered_feature_bc_matrix/barcodes.tsv.gz",
        "/storage/singlecell/zz4/fetal_snakemake/data/adult_data/10x3_Lobe_19_D019_NeuN-v7/possorted_genome_bam.bam",
    output:
       "/storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/10x3_Lobe_19_D019_NeuN-v7.loom",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate velocyto
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        mkdir /storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/
        velocyto run -o /storage/singlecell/zz4/fetal_snakemake/results/RNA_velocity/ -@ 12 --samtools-memory 20240 --bcfile /storage/singlecell/zz4/fetal_snakemake/data/adult_data/10x3_Lobe_19_D019_NeuN-v7/filtered_feature_bc_matrix/barcodes.tsv.gz -e 10x3_Lobe_19_D019_NeuN-v7 /storage/singlecell/zz4/fetal_snakemake/data/adult_data/10x3_Lobe_19_D019_NeuN-v7/possorted_genome_bam.bam {genome}'
        """