import pandas as pd

meta = pd.read_csv(
    "/storage/chentemp/zz4/adult_dev_compare/scripts/Volocity/velocyto/meta.csv"
)
samples = meta["samples"].tolist()
sample2barcodes = dict(zip(meta["samples"].tolist(), meta["barcodes"].tolist()))
sample2bams = dict(zip(meta["samples"].tolist(), meta["bams"].tolist()))
genome = "/storage/chentemp/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf"


def get_barcodes(wildcards):
    return sample2barcodes[wildcards.sample]


def get_bam(wildcards):
    return sample2bams[wildcards.sample]


rule all:
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/combined.loom",
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/combined.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated_ldata.h5ad",


rule velocyto:
    ## Run velocyto
    input:
        get_barcodes,
        get_bam,
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/{sample}.loom",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate velocyto
        export LC_ALL=en_US.utf-8
        export LANG=en_US.utf-8
        mkdir /storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/
        velocyto run -o /storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/ -@ 12 --samtools-memory 10240 --bcfile /storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/{wildcards.sample}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e {wildcards.sample} /storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/{wildcards.sample}/outs/gex_possorted_bam.bam {genome}'
        """


rule merge_looms:
    ## Run velocyto
    input:
        expand(
            "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/{sample}.loom",
            sample=samples,
        ),
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/combined.loom",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Volocity/merge_looms/merge_looms.py'
        """


rule convert_loom_to_h5ad:
    ## Run velocyto
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/combined.loom",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/combined.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Volocity/convert_loom_to_h5ad/convert_loom_to_h5ad.py'
        """


rule add_ldata_to_adata:
    ## Run velocyto
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/adata_object_UMAP/ALL.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/RNA_velocity/combined.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated_ldata.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Volocity/add_ldata_to_adata/add_ldata_to_adata.py'
        """
