import pandas as pd

meta = pd.read_csv(
    "/storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/ArchR_create_object/meta.csv"
)
samples = meta["Samples"].tolist()


rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj2/Save-ArchR-Project.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/Save-ArchR-Project.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/cellbygene/gene_score.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score_imputed.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/cellbygene/gene_score_imputed.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_umap/ATAC_UMAPHarmony_cor.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/GroupBigWigs/majorclass/AC-TileSize-100-normMethod-None-ArchR.bw",


rule ArchR_create_object:
    ## Create ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/Multi_Fetal_23w1d_NR/outs/atac_fragments.tsv.gz",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj1/Save-ArchR-Project.rds",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/ArchR_create_object/ArchR_create_object.R'
        """


rule ArchR_filter:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj1/Save-ArchR-Project.rds",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_filtered_cells/ATAC_Filtered_cell.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/ArchR_filter/ArchR_filter.R'
        """


rule create_seRNA:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/create_seRNA/create_seRNA.R",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/seRNA/seRNA.rds",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/create_seRNA/create_seRNA.R'
        """


rule add_seRNA:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/seRNA/seRNA.rds",
        "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/ALL.csv",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj2/Save-ArchR-Project.rds",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/add_seRNA/add_seRNA.R'
        """


rule run_umap:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj2/Save-ArchR-Project.rds",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/Save-ArchR-Project.rds",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/run_umap/run_umap.R'
        """


rule save_umap:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/Save-ArchR-Project.rds",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_umap/ATAC_UMAPHarmony_cor.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/save_umap/save_umap.R'
        """


rule export_gene_score_R:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/Save-ArchR-Project.rds",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score_colnames.txt",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/export_gene_score/export_gene_score.R'
        """


rule export_gene_score_python:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score_colnames.txt",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/cellbygene/gene_score.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/export_gene_score/export_gene_score.py'
        """


rule export_gene_score_python_imputation:
    ## Filter ArchR project
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/cellbygene/gene_score.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/gene_score/gene_score_imputed.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/cellbygene/gene_score_imputed.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/export_gene_score/export_gene_score_imputation.py'
        """


rule getGroupBW:
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/Save-ArchR-Project.rds",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ArchR/Save-proj3/GroupBigWigs/majorclass/AC-TileSize-100-normMethod-None-ArchR.bw",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/ATAC/getGroupBW/getGroupBW.R'
        """
