import pandas as pd

meta = pd.read_csv(
    "/storage/singlecell/zz4/fetal_snakemake/scripts/ATAC/ArchR_create_object/meta.csv"
)
samples = meta["Samples"].tolist()


rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/ArchR/Save-proj1/Save-ArchR-Project.rds",
        "/storage/singlecell/zz4/fetal_snakemake/results/ATAC_filtered_cells/ATAC_Filtered_cell.csv",


rule ArchR_create_object:
    ## Create ArchR project
    input:
        expand(
            [
                "/storage/singlecell/zz4/fetal_snakemake/data/Retina_fetal/{sample}/outs/atac_fragments.tsv.gz",
            ],
            sample=samples,
        ),
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/ArchR/Save-proj1/Save-ArchR-Project.rds",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/ATAC/ArchR_create_object/ArchR_create_object.R'
        """

rule ArchR_filter:
    ## Filter ArchR project
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/ArchR/Save-proj1/Save-ArchR-Project.rds"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/ATAC_filtered_cells/ATAC_Filtered_cell.csv",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/ATAC/ArchR_filter/ArchR_filter.R'
        """
