
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/17W1D_Fovea_retina -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Fovea_retina/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e 17W1D_Fovea_retina /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Fovea_retina/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/17W1D_Nasal_retina -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Nasal_retina/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e 17W1D_Nasal_retina /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Nasal_retina/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/17W1D_Temporal_retina -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Temporal_retina/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e 17W1D_Temporal_retina /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Temporal_retina/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_11w2d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_11w2d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_11w2d_FR_2 -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_FR_2/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_11w2d_FR_2 /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_FR_2/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_11w2d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_11w2d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_13W_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_13W_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_13W_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_13W_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_13W_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_13W_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_13W_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_13W_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_14w5d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_14w5d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_14w5d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_14w5d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_14w5d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_14w5d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_14w5d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_14w5d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_19W4d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_19W4d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_19W4d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_19W4d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_19W4d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_19W4d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_19W4d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_19W4d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_20W2d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_20W2d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_20W2d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_20W2d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_20W2d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_20W2d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_20W2d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_20W2d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_23w1d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_23w1d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_23w1d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_23w1d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multi_Fetal_23w1d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_23w1d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multi_Fetal_23w1d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_23w1d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_10w_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_10w_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_10w_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_10w_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_10w_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_10w_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_10w_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_10w_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_12w3d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_12w3d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_12w3d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_12w3d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_12w3d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_12w3d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_12w3d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_12w3d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_14w2d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_14w2d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_14w2d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_14w2d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_14w2d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_14w2d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_14w2d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_14w2d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_16w4d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_16w4d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_16w4d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_16w4d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_16w4d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_16w4d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_16w4d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_16w4d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_20w1d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_20w1d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_20w1d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_20w1d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_20w1d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_20w1d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_20w1d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_20w1d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_23w4d_FR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_23w4d_FR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_23w4d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_23w4d_FR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
slurmtaco.sh --g00 -m 20G -t 1 -- velocyto run -o /storage/singlecell/zz4/fetal_bash/results/RNA_velocity/Multiome_23w4d_NR -@ 12 --samtools-memory 10240 --bcfile /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_23w4d_NR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -e Multiome_23w4d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_23w4d_NR/outs/gex_possorted_bam.bam /storage/singlecell/zz4/Reference/refdata-cellranger-arc-GRCh38-2020-A/genes/genes.gtf
