meta=/storage/singlecell/zz4/fetal_bash/data/Retina_fetal_sample_meta.csv
reference=/storage/chen/data_share_folder/jinli/scpred/scPred_trainmodel_RNA_svmRadialWeights_scpred.rds
output_results_path=/storage/singlecell/zz4/fetal_bash/results/scPred/
output_figures_path=/storage/singlecell/zz4/fetal_bash/figures/scPred/
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_11w2d_FR_2 /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_11w2d_FR_2.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_11w2d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_11w2d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_11w2d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_11w2d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_13W_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_13W_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_13W_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_13W_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_14w5d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_14w5d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_14w5d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_14w5d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_19W4d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_19W4d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_19W4d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_19W4d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_20W2d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_20W2d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_20W2d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_20W2d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_23w1d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_23w1d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multi_Fetal_23w1d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multi_Fetal_23w1d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_10w_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_10w_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_10w_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_10w_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_12w3d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_12w3d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_12w3d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_12w3d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_14w2d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_14w2d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_14w2d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_14w2d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_16w4d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_16w4d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_16w4d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_16w4d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_20w1d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_20w1d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_20w1d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_20w1d_NR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_23w4d_FR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_23w4d_FR.rds $reference $meta $output_results_path $output_figures_path
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript scPred.R Multiome_23w4d_NR /storage/singlecell/zz4/fetal_bash/results/DoubletFinder_seurat_object//Multiome_23w4d_NR.rds $reference $meta $output_results_path $output_figures_path
