rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure5/Macula_upset_DEGs.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure5/venn_diagramm.png",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure5/sc.pl.heatmap_RPC.svg",
####################################################################################################

rule plot_upset:
    ## 
    input:
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure5/Macula_upset_DEGs.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure5/plot_upset.R'
        """

rule plot_venn:
    ## 
    input:
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure5/venn_diagramm.png",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure5/plot_venn.diagram.R'
        """

rule plot_RPC_DEG:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/merged_h5ad/merged_raw_filtered_umap_10000_woadult_MG.h5ad"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure5/sc.pl.heatmap_RPC.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure5/plot_RPC_DEG.py'
        """

