rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_gene_module_heatmap.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_WEEK.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_Days.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_MG_mv.velocity_embedding_stream_latent_time.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_MG_Modules_GO.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/overall_umap_by_majorclass_Peripheral_PCW10.svg",
####################################################################################################

rule plot_PRPC_MG_latent_time:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/pseudotime/PRPC_MG_latent_time.csv"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_WEEK.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_Days.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/plot_PRPC_MG_latent_time.py'
        """

rule plot_gene_module_latent_time_PRPC_MG:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/latent_time/PPRC_hs.create_modules.pkl",
        "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/latent_time/PPRC_hs.adata.pkl",
        "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/umap/PRPC_MG.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_gene_module_heatmap.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/plot_gene_module_latent_time_PRPC_MG.py'
        """

rule PRPC_MG_scv_pl_velocity_embedding_stream:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/PRPC_MG.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_MG_mv.velocity_embedding_stream_latent_time.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/PRPC_MG_scv.pl.velocity_embedding_stream.py'
        """

rule PRPC_MG_hotspot_modules_GO:
    ## 
    input:
        
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_MG_Modules_GO.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/PRPC_MG_hotspot_modules_GO.R'
        """

rule plot_PRPC_MG_split_by_region_days:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/PRPC_MG.h5ad"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/overall_umap_by_majorclass_Peripheral_PCW10.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/plot_PRPC_MG_split_by_region_days.py'
        """

