rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_gene_module_heatmap.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_Region.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_WEEK.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_Days.svg",

####################################################################################################

rule plot_PRPC_MG_latent_time:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/pseudotime/PRPC_MG_latent_time.csv"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_Region.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_WEEK.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/latent_time_Days.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/plot_PRPC_MG_latent_time.py'
        """

rule plot_gene_module_latent_time_PRPC_MG:
    ## 
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/latent_time/PPRC_hs.create_modules.pkl",
        "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/latent_time/PPRC_hs.adata.pkl",
        "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/umap/PRPC_MG.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure6/PRPC_gene_module_heatmap.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure6/plot_gene_module_latent_time_PRPC_MG.py'
        """


