rule all:
    input:
       "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/SCENT/PRPC_hs_local_correlations.csv",
       "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/monocle3/PRPC_hs_local_correlations.csv"

rule gene_module_analysis_PRPC_SCENT:
    ## gene_module_analysis_PRPC
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult.h5ad",
        "/storage/singlecell/zz4/fetal_snakemake/results/pseudotime/PRPC_MG_SCENT.csv",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/SCENT/PRPC_hs_local_correlations.csv"
    threads: 6
    shell:
        """
        bash -c '
        mkdir /storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/
        mkdir /storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/SCENT/
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/gene_module/gene_module_analysis_PRPC_SCENT.py'
        """

rule gene_module_analysis_PRPC_monocle3:
    ## gene_module_analysis_PRPC
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult.h5ad",
        "/storage/singlecell/zz4/fetal_snakemake/results/pseudotime/PRPC_MG_monocle3_pseudotime.csv",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/monocle3/PRPC_hs_local_correlations.csv"
    threads: 6
    shell:
        """
        bash -c '
        mkdir /storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/
        mkdir /storage/singlecell/zz4/fetal_snakemake/results/hotspot/PRPC/monocle3/
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/gene_module/gene_module_analysis_PRPC_monocle3.py'
        """
