import pandas as pd

rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Cell Birth Rate in the Macula.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Cell Birth Rate in the Peripheral.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/woadult_scv.pl.velocity_embedding_stream_scpred_prediction.png",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/wadult_scv.pl.velocity_embedding_stream_scpred_prediction.png",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Macula_cell_type_composition.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Peripheral_cell_type_composition.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_mv.velocity_embedding_stream.majorclass.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_mv.velocity_embedding_stream.Days.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_ccat.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_ccat_boxplot_majorclass.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Macula_PCW10.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_precursor_de_gene.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_mv.velocity_embedding_stream.latent_time.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_NRPC_DE.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/find_AC_NRPC.svg",
####################################################################################################

rule figure2_plot_cell_birth_rate:
    ## Seurat QC
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/filtered_major_class_MG.csv"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Cell Birth Rate in the Macula.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Cell Birth Rate in the Peripheral.svg"
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        mkdir /storage/singlecell/zz4/fetal_snakemake/figures/figure2
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/plot_cell_birth_rate.py'
        """

rule scv_pl_velocity_embedding_stream:
    ## Seurat QC
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/filtered_major_class_MG.csv"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/woadult_scv.pl.velocity_embedding_stream_scpred_prediction.png",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/wadult_scv.pl.velocity_embedding_stream_scpred_prediction.png"
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/scv.pl.velocity_embedding_stream.py'
        """

rule plot_cell_type_composition:
    ## Seurat QC
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/filtered_major_class_MG.csv"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Macula_cell_type_composition.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Peripheral_cell_type_composition.svg"
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/plot_cell_type_composition.py'
        """

rule AC_mv_velocity_embedding_stream:
    ## Seurat QC
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/AC.h5ad",
        "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/NRPC_AC.csv",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_mv.velocity_embedding_stream.majorclass.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_mv.velocity_embedding_stream.Days.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_mv.velocity_embedding_stream.latent_time.svg"
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/AC_mv.velocity_embedding_stream.py'
        """

rule AC_ccat:
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/AC.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_ccat.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_ccat_boxplot_majorclass.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/AC_ccat.py'
        """

rule AC_umap_seperate_by_time:
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/AC.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/Macula_PCW10.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/AC_umap_seperate_by_time.py'
        """

rule AC_precursor_DE_heatmap:
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/AC.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_precursor_de_gene.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/AC_precursor_DE_heatmap.py'
        """

rule AC_NRPC_DE_volcano:
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/AC.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/AC_NRPC_DE.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/AC_NRPC_DE_volcano.py
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/AC_NRPC_DE_volcano.R'
        """

rule Find_AC_NRPC:
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/multivelo_recover_dynamics_results/AC.h5ad",
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure2/find_AC_NRPC.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure2/Find_AC_NRPC.py'
        """