import scanpy as sc
import scvi
import os
import scvelo as scv
import anndata
import sys
import pandas as pd
import matplotlib.pyplot as plt
import cellrank as cr
import seaborn as sns
import numpy as np

# import CellRank kernels and estimators
from cellrank.external.kernels import WOTKernel
from cellrank.tl.kernels import ConnectivityKernel
from cellrank.tl.estimators import GPCCA

# set verbosity levels
cr.settings.verbosity = 2
scv.settings.verbosity = 3

scv.set_figure_params(dpi=300)

adata = scv.read(
    "/storage/singlecell/zz4/fetal_bash/results/merged_h5ad/merged_raw_filtered_umap_10000_major_sub_class.h5ad"
)

adata.obs["scpred_prediction"] = adata.obs.majorclass.replace(
    {
        "AC Precursor": "AC",
        "BC Precursor": "BC",
        "Cone Precursor": "Cone",
        "GABAergic": "AC",
        "Glycinergic": "AC",
        "HC0": "HC",
        "HC1": "HC",
        "MG": "MG",
        "ML_Cone": "Cone",
        "NRPC": "RPC",
        "OFF-BC": "BC",
        "OFF_MGC": "RGC",
        "ON-BC": "BC",
        "ON_MGC": "RGC",
        "PRPC": "RPC",
        "RBC": "BC",
        "RGC Precursor": "RGC",
        "Rod": "Rod",
        "Rod Precursor": "Rod",
        "SACs": "AC",
        "S_Cone": "Cone",
        "dual ACs": "AC",
    }
)

degenes = [
    "ABI3BP",
    "ABLIM3",
    "ADAMTSL1",
    "ANXA2",
    "ARSJ",
    "ASIC2",
    "BICDL1",
    "BMP7",
    "CALM1",
    "CCN1",
    "CDH12",
    "CDH20",
    "CGNL1",
    "CHRM3",
    "CNMD",
    "COL4A3",
    "CPA6",
    "CRABP1",
    "CYP26A1",
    "DDAH1",
    "DLGAP1",
    "DPP6",
    "EPHA3",
    "EPHA5",
    "ERBB4",
    "FAM135B",
    "FGF1",
    "FOS",
    "FOXD1",
    "FRMD3",
    "FRZB",
    "GLT1D1",
    "GNG3",
    "GNGT1",
    "HS6ST3",
    "KCND3",
    "KCNIP4",
    "KCNMA1",
    "LUM",
    "MAMDC2",
    "MCF2L2",
    "METTL24",
    "MIR99AHG",
    "MPZ",
    "MTUS2",
    "NEFL",
    "NEFM",
    "NPAS2",
    "NTNG1",
    "OVCH1",
    "P3H2",
    "PCDH8",
    "PCP4",
    "PDE6H",
    "PIEZO2",
    "PITPNM2",
    "PRR16",
    "RARB",
    "RBFOX1",
    "SAT1",
    "SLC8A1",
    "SLIT3",
    "SNCG",
    "SOX6",
    "SPOCK1",
    "TENM3",
    "TLL1",
    "TMEM132D",
    "TTC39B",
    "UNC13C",
    "UNC5C",
    "UNC5D",
    "VGLL3",
    "WNT5B",
    "ADAMTS3",
    "ADGB",
    "AGBL4",
    "AJAP1",
    "ANOS1",
    "APCDD1L",
    "ARHGAP18",
    "BAMBI",
    "BTG1",
    "C14orf39",
    "CADPS2",
    "CALCRL",
    "CCND1",
    "CDH7",
    "CFAP299",
    "CFAP47",
    "CHSY3",
    "CNTN5",
    "CNTNAP3",
    "COL13A1",
    "COL25A1",
    "COL6A6",
    "CP",
    "CPAMD8",
    "CPEB1",
    "CRABP2",
    "CYP1B1",
    "DAPL1",
    "DCC",
    "DHRS3",
    "DSP",
    "DTNA",
    "EFNA5",
    "EFNB2",
    "EPHA6",
    "EYA2",
    "FLRT2",
    "FREM2",
    "GLI3",
    "HES1",
    "HIST1H1E",
    "HIST1H4E",
    "HIVEP3",
    "HMX1",
    "HYDIN",
    "IL17RD",
    "ISLR2",
    "KANK4",
    "KCNC2",
    "KIRREL3",
    "KSR2",
    "L1TD1",
    "LEF1",
    "LHX9",
    "LRRTM3",
    "LRRTM4",
    "MAN1A1",
    "MIR548A1HG",
    "NECAB2",
    "OPCML",
    "PALMD",
    "PCDH9",
    "PDLIM5",
    "PTPRQ",
    "RALYL",
    "RAX",
    "RMST",
    "SLCO5A1",
    "SNCAIP",
    "STK32B",
    "STRA6",
    "SYTL4",
    "TBX5",
    "TRHDE",
    "TTC29",
    "TTYH2",
    "ZFP36L2",
    "ZFPM2",
    "ZIC1",
    "ADAMTS19",
    "ALDH1A1",
    "ALDH1A3",
    "ANKRD30BL",
    "ANO1",
    "C10orf67",
    "CCDC33",
    "CDKN2A",
    "CFAP54",
    "COL19A1",
    "COL8A1",
    "CPNE5",
    "CPNE8",
    "DIO3",
    "DIO3OS",
    "FGF19",
    "FGF8",
    "FOXI3",
    "FRAS1",
    "FRRS1",
    "GDF6",
    "GJA1",
    "GNG12",
    "KCNB2",
    "KITLG",
    "KLHL4",
    "LPAR1",
    "MECOM",
    "MIR503HG",
    "NPFFR2",
    "PACRG",
    "PLPP4",
    "PRAG1",
    "PTH2",
    "RASSF9",
    "SCN7A",
    "SERTM2",
    "SHISA9",
    "SLC6A20",
    "SLITRK1",
    "SPATA18",
    "SYT17",
    "TBX20",
    "TEC",
    "TEKT1",
    "TSHZ3",
    "TTC6",
    "AFAP1L2",
    "ALDH1A2",
    "ARHGAP22",
    "ARHGAP31",
    "C1orf61",
    "CARD18",
    "CD44",
    "CDKN1A",
    "CNTN6",
    "CNTNAP4",
    "COL1A1",
    "DIO2",
    "DIRC3",
    "EGR1",
    "FAM110B",
    "FAP",
    "FBXL14",
    "GATA3",
    "GRHL1",
    "GRID2",
    "GRIN2A",
    "IGSF21",
    "IL15",
    "LAMB1",
    "LIPG",
    "LIX1",
    "LRMDA",
    "LRRC4C",
    "MAN1C1",
    "MMP17",
    "MOXD1",
    "MTNR1A",
    "NEK6",
    "NHS",
    "NPVF",
    "NR4A1",
    "PCSK6",
    "POU3F2",
    "PPFIA2",
    "PTGDS",
    "PTGER3",
    "PVALB",
    "RHBDL3",
    "RHEX",
    "RNF144B",
    "S100A10",
    "SALL3",
    "SORBS1",
    "SORCS3",
    "SPTB",
    "SPTLC3",
    "SYNDIG1",
    "TGFA",
    "TMEM132C",
    "TMEM215",
    "TMTC1",
    "ZNF804B",
]

sc.pp.normalize_total(adata)
sc.pp.log1p(adata)


sc.tl.rank_genes_groups(adata, "majorclass")
NRPC = sc.get.rank_genes_groups_df(adata, group="NRPC")[1:20]
PRPC = sc.get.rank_genes_groups_df(adata, group="PRPC")[1:20]
sc.tl.rank_genes_groups(adata, "scpred_prediction")
MG = sc.get.rank_genes_groups_df(adata, group="MG")[1:10]
Rod = sc.get.rank_genes_groups_df(adata, group="Rod")[1:10]
BC = sc.get.rank_genes_groups_df(adata, group="BC")[1:10]
Cone = sc.get.rank_genes_groups_df(adata, group="Cone")[1:10]
HC = sc.get.rank_genes_groups_df(adata, group="HC")[1:10]
AC = sc.get.rank_genes_groups_df(adata, group="AC")[1:10]
RGC = sc.get.rank_genes_groups_df(adata, group="RGC")[1:10]

genes = list(
    set(
        list(NRPC.names)
        + list(PRPC.names)
        + list(MG.names)
        + list(BC.names)
        + list(AC.names)
        + list(HC.names)
        + list(RGC.names)
        + list(Cone.names)
        + list(Rod.names)
        + degenes
    )
)

print(len(genes))

adata = adata[:, genes]

sc.pp.filter_genes(adata, min_cells=3)
sc.pp.filter_cells(adata, min_genes=1)

sc.pp.pca(adata)
sc.pp.neighbors(adata)
sc.tl.umap(adata)

scv.pl.umap(adata, color="scpred_prediction")
scv.pl.umap(adata, color="Days")


adult = scv.read(
    "/storage/chenlab/Users/junwang/human_meta/data/ref/major_clean_major_scvi_Cluster_clean.h5ad"
)
adult.obs["Region"] = np.where(
    adult.obs.sampleid.isin(
        ["Chen_b_19D015_fovea", "Chen_b_19D014_fovea", "Chen_b_19D013_fovea"]
    ),
    "Macula",
    "Peripheral",
)

Macula = [
    "ABI3BP",
    "ABLIM3",
    "ADAMTSL1",
    "ANXA2",
    "ARSJ",
    "ASIC2",
    "BICDL1",
    "BMP7",
    "CALM1",
    "CCN1",
    "CDH12",
    "CDH20",
    "CGNL1",
    "CHRM3",
    "CNMD",
    "COL4A3",
    "CPA6",
    "CRABP1",
    "CYP26A1",
    "DDAH1",
    "DLGAP1",
    "DPP6",
    "EPHA3",
    "EPHA5",
    "ERBB4",
    "FAM135B",
    "FGF1",
    "FOS",
    "FOXD1",
    "FRMD3",
    "FRZB",
    "GLT1D1",
    "GNG3",
    "GNGT1",
    "HS6ST3",
    "KCND3",
    "KCNIP4",
    "KCNMA1",
    "LUM",
    "MAMDC2",
    "MCF2L2",
    "METTL24",
    "MIR99AHG",
    "MPZ",
    "MTUS2",
    "NEFL",
    "NEFM",
    "NPAS2",
    "NTNG1",
    "OVCH1",
    "P3H2",
    "PCDH8",
    "PCP4",
    "PDE6H",
    "PIEZO2",
    "PITPNM2",
    "PRR16",
    "RARB",
    "RARB",
    "RBFOX1",
    "SAT1",
    "SLC8A1",
    "SLIT3",
    "SNCG",
    "SOX6",
    "SPOCK1",
    "TENM3",
    "TLL1",
    "TMEM132D",
    "TTC39B",
    "UNC13C",
    "UNC5C",
    "UNC5D",
    "VGLL3",
    "WNT5B",
]
Peripheral = [
    "ADAMTS3",
    "ADGB",
    "AGBL4",
    "AJAP1",
    "ANOS1",
    "APCDD1L",
    "ARHGAP18",
    "BAMBI",
    "BTG1",
    "C14orf39",
    "CADPS2",
    "CALCRL",
    "CCND1",
    "CDH7",
    "CFAP299",
    "CFAP47",
    "CHSY3",
    "CNTN5",
    "CNTNAP3",
    "COL13A1",
    "COL25A1",
    "COL6A6",
    "CP",
    "CPAMD8",
    "CPEB1",
    "CRABP2",
    "CYP1B1",
    "DAPL1",
    "DCC",
    "DHRS3",
    "DSP",
    "DTNA",
    "EFNA5",
    "EFNB2",
    "EPHA6",
    "EYA2",
    "FLRT2",
    "FREM2",
    "GLI3",
    "HES1",
    "HIST1H1E",
    "HIST1H4E",
    "HIVEP3",
    "HMX1",
    "HYDIN",
    "IL17RD",
    "ISLR2",
    "KANK4",
    "KCNC2",
    "KCNIP4",
    "KIRREL3",
    "KSR2",
    "L1TD1",
    "LEF1",
    "LHX9",
    "LRRTM3",
    "LRRTM4",
    "MAN1A1",
    "MIR548A1HG",
    "NECAB2",
    "OPCML",
    "PALMD",
    "PCDH9",
    "PDLIM5",
    "PTPRQ",
    "RALYL",
    "RAX",
    "RMST",
    "SLCO5A1",
    "SNCAIP",
    "STK32B",
    "STRA6",
    "SYTL4",
    "TBX5",
    "TRHDE",
    "TTC29",
    "TTYH2",
    "ZFP36L2",
    "ZFPM2",
    "ZIC1",
]
sc.pl.dotplot(
    adata[adata.obs.Region.isin(["Macula", "Peripheral"])],
    [x for x in Macula if x in adata.var.index],
    groupby="Region",
    dendrogram=True,
)
sc.pl.dotplot(
    adult,
    [x for x in Macula if x in adult.var.index],
    groupby="Region",
    dendrogram=True,
)
sc.pl.dotplot(
    adata[adata.obs.Region.isin(["Macula", "Peripheral"])],
    [x for x in Peripheral if x in adata.var.index],
    groupby="Region",
    dendrogram=True,
)
sc.pl.dotplot(
    adult,
    [x for x in Peripheral if x in adult.var.index],
    groupby="Region",
    dendrogram=True,
)
adata.var.to_csv("/storage/singlecell/zz4/fetal_bash/temp/gene_panel.csv")