samples = [
    "Multi_Fetal_11w2d_FR",
    "Multi_Fetal_11w2d_FR_2",
    "Multi_Fetal_11w2d_NR",
    "Multi_Fetal_13W_FR",
    "Multi_Fetal_13W_NR",
    "Multi_Fetal_14w5d_FR",
    "Multi_Fetal_14w5d_NR",
    "Multi_Fetal_19W4d_FR",
    "Multi_Fetal_19W4d_NR",
    "Multi_Fetal_20W2d_FR",
    "Multi_Fetal_20W2d_NR",
    "Multi_Fetal_23w1d_FR",
    "Multi_Fetal_23w1d_NR",
    "Multiome_10w_FR",
    "Multiome_10w_NR",
    "Multiome_12w3d_FR",
    "Multiome_12w3d_NR",
    "Multiome_14w2d_FR",
    "Multiome_14w2d_NR",
    "Multiome_16w4d_FR",
    "Multiome_16w4d_NR",
    "Multiome_20w1d_FR",
    "Multiome_20w1d_NR",
    "Multiome_23w4d_FR",
    "Multiome_23w4d_NR",
    "sn_multiome_d59",
    "sn_multiome_d76c",
    "sn_multiome_d76p"]

meta_list = [
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/RPC_MG.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/NRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/PRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/AC_w_NRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/BC_w_NRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/Cone_w_NRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/HC_w_NRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/RGC_w_NRPC.csv",
    "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/Rod_w_NRPC.csv"]

groups = ["RPC_MG", "NRPC", "PRPC", "AC", "BC", "Cone", "HC", "RGC", "Rod"]

sample2meta = dict(zip(groups, meta_list))

output_result_path = (
    "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x/"
)
output_figure_path = (
    "/storage/chentemp/zz4/adult_dev_compare/figures/ATAC_aggregate_peaks_10x/"
)


def get_meta(wildcards):
    return sample2meta[wildcards.celltype]


rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/MultiVelo_filtered_cells/adata_rna.h5ad",
        expand(
            [
            "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_run_umap/{celltype}.h5ad"
            ],
            celltype=groups,
        ),
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_results/{celltype}.h5ad"
            ],
            celltype=groups,
        ),

rule multivelo_prepare_create_atac:
    ## multivelo_prepare_create_atac
    input:
        "/storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/{sample}/outs/atac_peak_annotation.tsv",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x/{sample}.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_prepare_create_atac/multivelo_prepare_create_atac.py /storage/chentemp/zz4/adult_dev_compare/data/Retina_fetal/{wildcards.sample} {wildcards.sample} {output_result_path} {output_figure_path};'
        """

output_result_path2 = "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x_noramlized/"

rule multivelo_normalize_atac_TF:
    ## multivelo_normalize_atac_TF
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x/{sample}.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x_noramlized/{sample}.h5ad",
    shell:
        """
        bash -c '
        mkdir /storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x_noramlized/
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_normalize_atac_TF/multivelo_normalize_atac_TF.py /storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x/{wildcards.sample}.h5ad {wildcards.sample} {output_result_path2};'
        """

rule multivelo_shared_barcodes_RNA_ATAC:
    ## multivelo_normalize_atac_TF
    input:
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_aggregate_peaks_10x_noramlized/{sample}.h5ad",
            ],
            sample=samples,
        ),
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/MultiVelo_filtered_cells/adata_rna.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/MultiVelo_filtered_cells/adata_atac.h5ad"
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_shared_barcodes_RNA_ATAC/multivelo_shared_barcodes_RNA_ATAC.py'
        """

rule multivelo_seurat_wnn:
    ## multivelo_normalize_atac_TF
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/MultiVelo_filtered_cells/adata_rna.h5ad",
        meta=get_meta,
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_seurat_wnn/{celltype}_nn_idx.txt",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        /storage/chen/home/zz4/miniforge-pypy3/envs/R/bin/Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_seurat_wnn/multivelo_seurat_wnn.R {input.meta} {wildcards.celltype};'
        """

rule multivelo_knn_smooth_chrom:
    ## multivelo_knn_smooth_chrom
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/MultiVelo_filtered_cells/adata_atac.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_seurat_wnn/{sam}_nn_idx.txt",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_knn_smooth_chrom/{sam}.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_knn_smooth_chrom/multivelo_knn_smooth_chrom.py {wildcards.sam};'
        """

rule multivelo_recover_dynamics_run_umap:
    ## multivelo_recover_dynamics_run_umap
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_knn_smooth_chrom/{celltype}.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_run_umap/{celltype}.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_recover_dynamics_run_umap/multivelo_recover_dynamics_run_umap.py {wildcards.celltype};'
        """

rule multivelo_recover_dynamics_chrom:
    ## multivelo_recover_dynamics_chrom
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_run_umap/{celltype}.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_results/{celltype}.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_recover_dynamics_chrom/multivelo_recover_dynamics_chrom.py {wildcards.celltype};'
        """

rule multivelo_infer_latent_time_PRPC:
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_results/RPC_MG.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/multivelo_recover_dynamics_latent_time/PRPC.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Multivelo/multivelo_infer_latent_time/multivelo_infer_latent_time_PRPC.py;'
        """
