import pandas as pd

meta = pd.read_csv(
    "/storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/QC_seurat/meta.csv"
)
samples = meta["Samples_ID"].tolist()
sample2file = dict(zip(meta["Samples_ID"].tolist(), meta["Samples"].tolist()))
labels = ["fetal", "fetal_adult"]
cell_type = ["AC", "BC", "Cone", "HC", "MG", "NRPC", "PRPC", "RGC", "Rod"]
NR = ["AC", "BC", "Cone", "HC", "RGC", "Rod", "RPC_MG", "ALL"]


def get_rawh5(wildcards):
    return sample2file[wildcards.sample]


rule all:
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Rod_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/AC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/BC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Cone_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/HC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/RGC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated_not_filter_ATAC.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated.h5ad",
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/adata_object_UMAP/{nr}.h5ad",
            ],
            nr=NR,
        ),
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_wadult_umap_10000.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/RGC_annotation_adult/RGC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/AC_annotation_adult/AC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/HC_annotation_adult/HC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/BC_annotation_adult/BC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/Rod_annotation_adult/Rod_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/Cone_annotation_adult/Cone_merged_object.h5ad",
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/{cy}.csv",
            ],
            cy=cell_type,
        ),
        "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/ALL.csv",


####################################################################################################
# Annotation
rule QC_seurat:
    ## Seurat QC
    input:
        get_rawh5,
    output:
        result="/storage/chentemp/zz4/adult_dev_compare/results/after_qc_seurat_object/{sample}.rds",
        figure="/storage/chentemp/zz4/adult_dev_compare/figures/after_qc_seurat_object/{sample}_seurat_QC.svg",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/QC_seurat/QC_seurat.R {wildcards.sample} {input} 200 10 /storage/chentemp/zz4/adult_dev_compare/results/after_qc_seurat_object/ /storage/chentemp/zz4/adult_dev_compare/figures/after_qc_seurat_object/'
        """


rule QC_seurat_apply_filter:
    ## Apply QC cutoff to get a subset of cells
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/after_qc_seurat_object/{sample}.rds",
    output:
        result="/storage/chentemp/zz4/adult_dev_compare/results/after_qc_seurat_object_apply_filter/{sample}.rds",
        figure="/storage/chentemp/zz4/adult_dev_compare/figures/after_qc_seurat_object_apply_filter/{sample}_after_filtered_seurat_QC.svg",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/QC_seurat_apply_filter/QC_seurat_apply_filter.R {wildcards.sample} {input} /storage/chentemp/zz4/adult_dev_compare/results/after_qc_seurat_object_apply_filter/ /storage/chentemp/zz4/adult_dev_compare/figures/after_qc_seurat_object_apply_filter/'
        """


rule DoubletFinder:
    ## Run DoubletFinder
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/after_qc_seurat_object_apply_filter/{sample}.rds",
    output:
        result="/storage/chentemp/zz4/adult_dev_compare/results/DoubletFinder_seurat_object/{sample}.rds",
        figure="/storage/chentemp/zz4/adult_dev_compare/figures/DoubletFinder_UMAP/{sample}.svg",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/DoubletFinder/DoubletFinder.R {wildcards.sample} {input} /storage/chentemp/zz4/adult_dev_compare/results/DoubletFinder_seurat_object/ /storage/chentemp/zz4/adult_dev_compare/figures/DoubletFinder_UMAP/'
        """


rule DoubletFinder_save_filtered_cells:
    ## Export DoubletFinder results to a csv file
    input:
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/DoubletFinder_seurat_object/{sample}.rds",
            ],
            sample=samples,
        ),
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/DoubletFinder_filtered_cells/DoubletFinder_filtered_cells.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/DoubletFinder_save_filtered_cells/DoubletFinder_save_filtered_cells.R'
        """


rule merge_rna_save_as_seurat_object:
    ## Merge all samples and save as seurat object.
    input:
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/DoubletFinder_seurat_object/{sample}.rds",
            ],
            sample=samples,
        ),
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_rna/merged_rna.rds",
    shell:
        """
        bash -c '
        mkdir /storage/chentemp/zz4/adult_dev_compare/results/merged_rna/
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate R
        Rscript /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/merge_rna_save_as_seurat_object/merge_rna_save_as_seurat_object.R'
        """


rule merge_feature_bc_matrix_to_h5ad:
    ## Merge all samples and save as anndata object, save the object and filtered object
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/DoubletFinder_filtered_cells/DoubletFinder_filtered_cells.csv",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/merge_feature_bc_matrix_to_h5ad/merge_feature_bc_matrix_to_h5ad.py'
        """


rule major_class_annotation:
    ## Annote major cell types with adult data. Progenitors were labeled as MG.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_wadult_umap_10000.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/filtered_major_class.csv",
    shell:
        """
        bash -c '
        export CUDA_VISIBLE_DEVICES=1
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/major_class_annotation/major_class_annotation.py'
        """


rule run_UMAP_to_without_adult:
    ## Run scvi umap to annotate MG cells. Filter cells based on ATAC and RNA seq
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/filtered_major_class.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult.h5ad",
    shell:
        """
        bash -c '
        export CUDA_VISIBLE_DEVICES=1
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/run_UMAP_to_without_adult/run_UMAP_to_without_adult.py'
        """


rule subclass_annotation_with_adult:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/RGC_annotation_adult/RGC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/AC_annotation_adult/AC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/HC_annotation_adult/HC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/BC_annotation_adult/BC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/Rod_annotation_adult/Rod_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/Cone_annotation_adult/Cone_merged_object.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python
        sh /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/subclass_annotation_with_adult/subclass_annotation_with_adult.sh'
        """


rule add_adult_annotated_reference_to_object:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/RGC_annotation_adult/RGC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/AC_annotation_adult/AC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/HC_annotation_adult/HC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/BC_annotation_adult/BC_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/Rod_annotation_adult/Rod_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation/Cone_annotation_adult/Cone_merged_object.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/data/manual_reference/AC_subclass_annotation.csv",
        "/storage/chentemp/zz4/adult_dev_compare/data/manual_reference/BC_subclass_annotation.csv",
        "/storage/chentemp/zz4/adult_dev_compare/data/manual_reference/Cone_subclass_annotation.csv",
        "/storage/chentemp/zz4/adult_dev_compare/data/manual_reference/HC_subclass_annotation.csv",
        "/storage/chentemp/zz4/adult_dev_compare/data/manual_reference/RGC_subclass_annotation.csv",
        "/storage/chentemp/zz4/adult_dev_compare/data/manual_reference/Rod_subclass_annotation.csv",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Rod_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/AC_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/BC_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Cone_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/HC_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/RGC_subtype.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python;
        cd /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/add_adult_annotated_reference_to_object/;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 AC_subtype_annotate.py;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 Cone_subtype_annotate.py; 
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 RGC_subtype_annotate.py;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 BC_subtype_annotate.py;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 HC_subtype_annotate.py;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 Rod_subtype_annotate.py'
        """


rule add_adult_annotated_reference_to_object_step2:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Rod_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/AC_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/BC_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Cone_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/HC_subtype.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/RGC_subtype.csv",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Rod_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/AC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/BC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Cone_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/HC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/RGC_subtype_processed.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python;
        cd /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/add_adult_annotated_reference_to_object_step2/;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 AC_subtype_annotate.py &
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 Cone_subtype_annotate.py & 
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 RGC_subtype_annotate.py &
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 BC_subtype_annotate.py &
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 HC_subtype_annotate.py &
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 Rod_subtype_annotate.py'
        """


rule organize_annotation:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Rod_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/AC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/BC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/Cone_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/HC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/cell_annotation_results/subclass_annotation_result_csv/RGC_subtype_processed.csv",
        "/storage/chentemp/zz4/adult_dev_compare/results/ATAC_filtered_cells/ATAC_Filtered_cell.csv",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated_not_filter_ATAC.h5ad",
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated.h5ad",
        expand(
            [
                "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/{cy}.csv",
            ],
            cy=cell_type,
        ),
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/organize_annotation/organize_annotation.py'
        """


rule run_umap_check_subclass_annotation:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/adata_object_UMAP/{nr}.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/run_umap_check_subclass_annotation/run_umap_check_subclass_annotation.py {wildcards.nr}'
        """


rule save_annotation_after_check:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/adata_object_UMAP/ALL.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/results/Annotation/ALL.csv",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/save_annotation_after_check/save_annotation_after_check.py'
        """


rule create_cell_by_gene_matrix:
    ## Run subclass annotation within each major class.
    input:
        "/storage/chentemp/zz4/adult_dev_compare/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_annotated.h5ad",
    output:
        "/storage/chentemp/zz4/adult_dev_compare/cellbygene/gene_expression.h5ad",
    shell:
        """
        bash -c '
        source /storage/chen/home/zz4/miniforge-pypy3/etc/profile.d/conda.sh && conda activate python;
        /storage/chen/home/zz4/miniforge-pypy3/envs/python/bin/python3.9 /storage/chentemp/zz4/adult_dev_compare/scripts/Annotation/create_cell_by_gene_matrix/create_cell_by_gene_matrix.py'
        """
