import scanpy as sc
import pandas as pd
import tempfile
import scvi
import scvelo as scv
import os

# Import packages
import scvelo as scv
import matplotlib.pyplot as plt
import pandas as pd
import scanpy as sc
import numpy as np


def run_umap_scvi(adata):
    f = tempfile.mkstemp(suffix=".h5ad")[1]
    adata.write(f)
    sc.pp.highly_variable_genes(
        adata, flavor="seurat_v3", n_top_genes=10000, subset=True
    )
    scvi.settings.seed = 0
    scvi.model.SCVI.setup_anndata(adata, batch_key="sampleid", labels_key="majorclass")
    vae = scvi.model.SCVI(adata, n_layers=2, n_latent=30, gene_likelihood="nb")
    vae.train()
    adata.obsm["X_scVI"] = vae.get_latent_representation()

    sc.pp.neighbors(adata, use_rep="X_scVI")
    sc.tl.leiden(adata)
    sc.tl.umap(adata)

    temp = scv.read(f)
    os.remove(f)
    temp.obs["leiden"] = adata.obs.leiden
    temp.obsm["X_scVI"] = adata.obsm["X_scVI"]
    temp.obsm["X_umap"] = adata.obsm["X_umap"]
    return temp


adata = scv.read(
    "/storage/singlecell/zz4/fetal_snakemake/results/merged_h5ad/merged_raw_filtered_umap_10000_woadult_MG.h5ad"
)

adata.obs["scpred_prediction"] = adata.obs.majorclass.replace(
    {
        "NRPC": "RPC",
        "PRPC": "RPC",
    }
)
adata.obs["scpred_prediction"] = pd.Categorical(
    list(adata.obs["scpred_prediction"]),
    categories=[
        "RPC",
        "RGC",
        "Cone",
        "HC",
        "AC",
        "Rod",
        "BC",
        "MG",
    ],
)

adata.obs["Days"] = adata.obs["Days"].astype(float)

#############################################################################################################################
## Plot subtype
adata.obs["subclass"] = ""
adata.obs.loc[adata.obs.majorclass == "PRPC", "subclass"] = "PRPC"
adata.obs.loc[adata.obs.majorclass == "NRPC", "subclass"] = "NRPC"
adata.obs.loc[adata.obs.majorclass == "MG", "subclass"] = "MG"
for file in [
    "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/AC_subtype.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/BC_subtype.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/Cone_subtype.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/HC_subtype.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/RGC_subtype.csv",
    "/storage/singlecell/zz4/fetal_snakemake/results/cell_annotation_results/Rod_subtype.csv",
]:
    df = pd.read_csv(file)
    df.index = df["Unnamed: 0"].values
    adata.obs.loc[df.index, "subclass"] = df.subclass

adata = adata[adata.obs["subclass"] != "",:]
genes = [
    "TFAP2D",
    "TFAP2C",
    "HMGXB4",
    "MYBL2",
    "SLC32A1",
    "GABPB1",
    "RP1",
    "CRX",
    "HLF",
    "PRPH2",
    "ISL1",
    "HES1",
    "DLX2",
    "ELL2",
    "EGR1",
    "TSHZ3",
    "AHR",
    "SNAI1",
    "SOX9",
    "SCRT2",
    "OPN1SW",
    "PBX4",
    "GADD45G",
    "RAX",
    "GABBR2",
    "UNC13C",
    "CUX2",
    "VSX2",
    "SMAD7",
    "MOB3B",
    "RPE65",
    "CDH20",
    "PPARA",
    "TANC1",
    "LHX4",
    "EPAS1",
    "STAT3",
    "PRDM5",
    "RIMS1",
    "FAM184B",
    "SLC1A3",
    "PIP5K1B",
    "CDK6",
    "RUNX1T1",
    "TIMP3",
    "ASCL1",
    "RLBP1",
    "ST18",
    "ARID5B",
    "DOCK1",
    "AKAP6",
    "POU4F2",
    "BARX2",
    "TCF7L1",
    "ADAMTS18",
    "ZIC1",
    "FEZF2",
    "GRIA1",
    "AFF2",
    "BACH1",
    "UNC5D",
    "NCOA1",
    "SMAD6",
    "BTG2",
    "IRX6",
    "ISL2",
    "SOX8",
    "FGF19",
    "LMX1A",
    "NEUROD1",
    "TAFA4",
    "PRICKLE2",
    "SHROOM3",
    "RHO",
    "LRFN5",
    "PKNOX2",
    "NHLH1",
    "ZNF804A",
    "MCC",
    "JUNB",
    "FOS",
    "ONECUT1",
    "SLN",
    "FSTL5",
    "PRKCE",
    "ETV5",
    "NEGR1",
    "INSM2",
    "USH2A",
    "ARR3",
    "REST",
    "INSM1",
    "WNT5B",
    "PCP2",
    "HMGA1",
    "NEUROG2",
    "EBF1",
    "ZHX2",
    "MITF",
    "NEUROG1",
    "UNCX",
    "GPM6B",
    "PLAG1",
    "MID1",
    "EML4",
    "NHLH2",
    "ZEB1",
    "IRX5",
    "TMEM108",
    "SOX11",
    "ZBTB7A",
    "E2F7",
    "GLIS3",
    "SOX2",
    "CLVS1",
    "NETO1",
    "SMAD3",
    "XKR4",
    "SLC24A3",
    "NFATC3",
    "RARB",
    "NR4A3",
    "SOX1",
    "KCNH7",
    "ZNF804B",
    "EFNA5",
    "GABRG3",
    "TAL2",
    "RORA",
    "NPAS2",
    "ZBTB16",
    "NR4A2",
    "ESR2",
    "TOX2",
    "EYS",
    "E2F1",
    "ZNF93",
    "RUNX1",
    "NR3C2",
    "LIN28B",
    "FOXN3",
    "DDIT3",
    "NPAS3",
    "CNTN1",
    "TBX3",
    "GNAT2",
    "NFAT5",
    "MAK",
    "HEY1",
    "THRB",
    "ZBTB20",
    "GRM7",
    "CREB5",
    "HMX3",
    "GAD1",
    "PLEKHG1",
    "PDE3A",
    "RXRG",
    "ASIC2",
    "NFIX",
    "COL4A2",
    "NAV2",
    "TOX",
    "GLI2",
    "PCDH11X",
    "DLX1",
    "E2F2",
    "FOXM1",
    "RGS7",
    "SLC35F3",
    "DISC1",
    "PRKN",
    "PROX1",
    "PLXNA2",
    "LHX9",
    "KCNT2",
    "SASH1",
    "HIVEP2",
    "RALGPS2",
    "MYB",
    "TMEM244",
    "PTPRK",
    "HEY2",
    "EBF3",
    "MKI67",
    "NR2E1",
    "PRDM1",
    "GRIK2",
    "PRDM13",
    "TCF7L2",
    "NTNG1",
    "ABCA4",
    "BARHL2",
    "TSHZ2",
    "LHX3",
    "ELAVL4",
    "AGBL4",
    "FOXO6",
    "HEYL",
    "FOXP4",
    "PBX3",
    "ATOH7",
    "PRKG1",
    "ASTN2",
    "SLC18A3",
    "DRGX",
    "ID3",
    "NRP1",
    "SP5",
    "TFDP1",
    "DYNC2H1",
    "ID1",
    "FGF14",
    "GAD2",
    "TLE4",
    "VSX1",
    "PRUNE2",
    "DCT",
    "MLLT10",
    "GPC5",
    "KLF9",
    "POU4F1",
    "PLXDC2",
    "HIF3A",
    "HES2",
    "PCDH9",
    "TP73",
    "HES5",
    "HIVEP1",
    "ELF2",
    "FOXO1",
    "LHFPL6",
    "TFAP2A",
    "PAM",
    "SMAD9",
    "RREB1",
    "LINGO2",
    "EDIL3",
    "NFIB",
    "ADAMTS6",
    "SIPA1L1",
    "ADARB2",
    "LCORL",
    "KANK1",
    "ONECUT3",
    "OLIG2",
    "SEMA5A",
    "DOK6",
    "POU2F2",
    "LRP1B",
    "EPHA6",
    "RFX4",
    "NRF1",
    "MAF",
    "TFAP2B",
    "NR4A1",
    "ZHX1",
    "PMEPA1",
    "GLI3",
    "FOXB1",
    "PDE1C",
    "ID2",
    "SOX6",
    "NRL",
    "PPARG",
    "EGFLAM",
    "ELAVL2",
    "MEIS2",
    "TRPM1",
    "ZFHX3",
    "GRIP1",
    "PTPRM",
    "DLGAP1",
    "TGIF1",
    "DSCAM",
    "HMX1",
    "KAZN",
    "LHFPL3",
    "NFIA",
    "HMGA2",
    "DPP6",
    "MTA3",
    "ETV1",
    "TBX5",
    "DCDC1",
    "FOXO3",
    "NLK",
    "PRR16",
    "TOX3",
    "ZFPM2",
    "PRDM6",
    "ESRRG",
    "FOXP2",
    "OTX2",
    "HES6",
    "LRRTM4",
    "SAG",
    "ZEB2",
    "MEIS1",
    "GULP1",
    "THSD7B",
    "CADPS2",
    "PRKCA",
    "DAB1",
    "PRDM8",
    "FRMD5",
    "SATB1",
    "ZFHX2",
    "STK3",
    "NR2F2",
    "ZHX3",
    "SKOR2",
    "ADGRV1",
    "MDGA2",
    "DLG2",
    "CNTN4",
    "JAZF1",
    "MXD3",
    "HOTAIRM1",
    "CPNE4",
    "CNTNAP5",
    "GNAT1",
    "IKZF2",
    "ATXN1",
    "TNIK",
    "TP63",
    "DPF1",
    "PDZD2",
    "NFIC",
    "POU2F1",
    "FMN2",
    "PROM1",
    "BEST1",
    "SOX5",
    "NAALADL2",
    "CNTNAP2",
    "ROBO1",
    "MECOM",
    "ARHGEF26",
    "FOXN4",
    "PTPRG",
    "CARMIL1",
    "FRMD4B",
    "RXRA",
    "SHOX2",
    "DACH2",
    "KLHL29",
    "NR6A1",
    "LHX2",
    "BCL11A",
    "ONECUT2",
    "HIVEP3",
    "DMD",
    "OVOL2",
    "CTNNA3",
    "TFDP2",
    "LEF1",
    "GALNTL6",
    "NSD2",
    "HHIP",
    "PTPN13",
    "TENM3",
    "PCDH7",
    "IRX4",
    "MYO10",
    "E2F5",
    "RALYL",
    "GRM6",
    "POU6F2",
    "TENM2",
    "EBF2",
    "MYBL1",
    "PAX5",
    "CNTN5",
    "PLEKHA7",
    "TEAD1",
    "E2F8",
    "GRAMD1B",
    "PAUPAR",
    "GRIA4",
    "PPP2R2B",
    "E2F3",
    "SEMA6D",
    "CSMD1",
    "BACH2",
    "TMTC1",
    "NTM",
    "PBX1",
    "TRERF1",
    "ARNTL2",
    "PDE4D",
    "POU6F1",
    "HOPX",
    "MEG8",
    "RAX2",
    "TCF12",
    "MEF2A",
    "MESP2",
    "LRRC7",
    "SCRT1",
    "RBFOX1",
    "CRYM",
    "SALL3",
    "SPON1",
    "BRIP1",
    "PITPNC1",
    "TCF3",
    "CELF4",
    "RFX2",
    "ZBTB7C",
    "MIR924HG",
    "LINC01515",
    "CPEB1",
    "GRID2",
    "TGIF2",
    "SORCS1",
    "OPCML",
    "MTUS2",
    "DACH1",
    "PARD3B",
    "LHX1",
    "SDK1",
    "FMN1",
    "PLCB1",
    "RFX3",
    "NR2E3",
    "SP8",
    "NHS",
    "LUZP2",
    "SLIT2",
    "ZBTB18",
    "NKAIN3",
    "LINC01572",
    "SRGAP1",
    "TCF4",
    "NYAP2",
    "NRXN1",
    "ZBTB38",
    "HCN1",
    "MEF2C",
    "PTF1A",
    "KCNMA1",
    "PAX6",
    "TRPS1",
    "SNTG1",
    "CCDC88A",
    "HOXA1",
    "PRKCB",
    "CTCF",
    "ESRRB",
    "EPS8",
    "LINC00511",
    "MYT1L",
    "TFAP2E",
    "ANO2",
    "DSCAML1",
    "ZFHX4",
    "MXI1",
    "MYC",
    "RMST",
    "LINC01414",
    "SLC6A9",
    "FOXP1",
    "NEBL",
]

adata = adata[:, genes]
adata = run_umap_scvi(adata)
adata.write("/storage/singlecell/zz4/fetal_snakemake/temp/adata.h5ad")
sc.pl.umap(
    adata,
    color="subclass",
    size=5,
    legend_loc="on data",
    title="",
    return_fig=True,
    frameon=False,
    legend_fontweight="bold",
    legend_fontoutline=True,
)
fig = plt.gcf()
fig.set_size_inches(10, 10)
plt.savefig(
    "/storage/singlecell/zz4/fetal_snakemake/temp/overall_umap_by_subtype.svg",
    dpi=600,
    bbox_inches="tight",
    transparent=True,
    backend="cairo",
)

sc.pl.umap(
    adata,
    color="majorclass",
    size=5,
    legend_loc="on data",
    title="",
    return_fig=True,
    frameon=False,
    legend_fontweight="bold",
    legend_fontoutline=True,
)
fig = plt.gcf()
fig.set_size_inches(10, 10)
plt.savefig(
    "/storage/singlecell/zz4/fetal_snakemake/temp/overall_umap_by_majortype.svg",
    dpi=600,
    bbox_inches="tight",
    transparent=True,
    backend="cairo",
)
