min_cells=10
min_features=200
output_figures_path=/storage/singlecell/zz4/fetal_bash/figures/qc_seurat_object/
output_results_path=/storage/singlecell/zz4/fetal_bash/results/qc_seurat_object/
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R 17W1D_Fovea_retina /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Fovea_retina/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R 17W1D_Nasal_retina /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Nasal_retina/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R 17W1D_Temporal_retina /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/17W1D_Temporal_retina/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_11w2d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_11w2d_FR_2 /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_FR_2/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_11w2d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_11w2d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_13W_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_13W_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_13W_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_13W_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_14w5d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_14w5d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_14w5d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_14w5d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_19W4d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_19W4d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_19W4d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_19W4d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_20W2d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_20W2d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_20W2d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_20W2d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_23w1d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_23w1d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multi_Fetal_23w1d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multi_Fetal_23w1d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_10w_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_10w_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_10w_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_10w_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_12w3d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_12w3d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_12w3d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_12w3d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_14w2d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_14w2d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_14w2d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_14w2d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_16w4d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_16w4d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_16w4d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_16w4d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_20w1d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_20w1d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_20w1d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_20w1d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_23w4d_FR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_23w4d_FR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
slurmtaco.sh -p short -m 10G -t 1 -- /storage/chen/home/zz4/anaconda3/envs/r/bin/Rscript QC_seurat.R Multiome_23w4d_NR /storage/singlecell/zz4/fetal_bash/data/Retina_fetal/Multiome_23w4d_NR/outs/filtered_feature_bc_matrix.h5 $min_cells $min_features $output_figures_path $output_results_path;
