rule all:
    ## Put input file here to run corresponding rules
    input:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/gene_score_heatmap.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/gene_expression_heatmap.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_cell_type.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_atac_umap_by_cell_type.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_days.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_subtype.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_cell_type_Peripheral_PCW20.svg"

####################################################################################################

rule figure1_plot_gene_score_gene_expression_heatmap:
    ## plot gene score and gene expression heatmap
    input:
         "/storage/singlecell/zz4/fetal_snakemake/results/ArchR/gene_score/gene_score.h5ad",
         "/storage/singlecell/zz4/fetal_snakemake/results/merged_h5ad/merged_raw_filtered_umap_10000_wadult_MG.h5ad"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/gene_score_heatmap.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/gene_expression_heatmap.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        mkdir /storage/singlecell/zz4/fetal_snakemake/figures/figure1
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure1/plot_gene_score_gene_expression_heatmap.py'
        """

rule figure1_plot_overall_umap:
    ## Plot overall umap color by cell type
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/merged_h5ad/merged_raw_filtered_umap_10000_woadult_MG.h5ad"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_cell_type.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_days.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_region.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_subtype.svg",
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_umap_by_cell_type_Peripheral_PCW20.svg"
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure1/plot_overall_umap.py'
        """

rule figure1_plot_atac_umap_output_umap_from_archr:
    ## Output ATAC umap to csv file, and plot UMAP
    input:
        "/storage/singlecell/zz4/fetal_snakemake/results/ArchR/Save-proj2/Save-ArchR-Project.rds"
    output:
        "/storage/singlecell/zz4/fetal_snakemake/figures/figure1/overall_atac_umap_by_cell_type.svg",
    shell:
        """
        bash -c '
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate r
        Rscript /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure1/plot_ATAC_seq_UMAP.R
        source /storage/singlecell/zz4/mambaforge/etc/profile.d/conda.sh && conda activate python
        python3.9 /storage/singlecell/zz4/fetal_snakemake/scripts/figures/figure1/plot_ATAC_seq_UMAP.py'
        """

